In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

veriler=pd.read_csv("Wine.csv")
X=veriler.iloc[:,0:13].values
y=veriler.iloc[:,13].values

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [9]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=2)

X_train2=lda.fit_transform(X_train,y_train)
X_test2=lda.transform(X_test)

In [10]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression(random_state=0)
lg.fit(X_train,y_train)

lg2=LogisticRegression(random_state=0)
lg2.fit(X_train2,y_train)

y_pred=lg.predict(X_test)
y_pred2=lg2.predict(X_test2)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

cm2=confusion_matrix(y_test,y_pred2)
print(cm2)

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
