In [1]:
import numpy as np


In [2]:
liste=[20,30,40]

In [3]:
type(liste)

list

In [4]:
np.array(liste)

array([20, 30, 40])

In [5]:
matrixListesi=[[10,20,30],[1,2,3],[30,40,50]]

In [6]:
matrixListesi

[[10, 20, 30], [1, 2, 3], [30, 40, 50]]

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [ 1,  2,  3],
       [30, 40, 50]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.linspace(0,30,12)

array([ 0.        ,  2.72727273,  5.45454545,  8.18181818, 10.90909091,
       13.63636364, 16.36363636, 19.09090909, 21.81818182, 24.54545455,
       27.27272727, 30.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.randn(1,5)

array([[0.63281776, 1.61607707, 0.31545419, 0.03719665, 0.25264636]])

In [24]:
np.random.randint(0,10,2)

array([9, 0], dtype=int32)

In [2]:
import numpy as np
myArray=np.arange(0,15)

In [4]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
myArray[3:8]

array([3, 4, 5, 6, 7])

In [8]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])