In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
#yaprak sınıfını bulma

In [45]:
veriler=pd.read_excel("Iris.xls")
X=veriler.iloc[:,0:4].values
Y=veriler.iloc[:,-1:].values

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=0)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [47]:
#logistic regresssion
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression(random_state=0)
y_pred=log_reg.fit(X_train,y_train.ravel()).predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)


[[16  0  0]
 [ 0 18  1]
 [ 0  2 13]]


In [48]:
#knn
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric="minkowski")
y_pred=knn.fit(X_train,y_train.ravel()).predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)


[[16  0  0]
 [ 0 18  1]
 [ 0  1 14]]


In [54]:
#SVM
from sklearn.svm import SVC
svc=SVC(kernel="linear")
y_pred=svc.fit(X_train,y_train.ravel()).predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]]


In [50]:
#naive bayes
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
y_pred=gnb.fit(X_train,y_train.ravel()).predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[16  0  0]
 [ 0 19  0]
 [ 0  2 13]]


In [51]:
#decision tree
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion="entropy")
y_pred=dtc.fit(X_train,y_train.ravel()).predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)


[[16  0  0]
 [ 0 18  1]
 [ 0  1 14]]


In [58]:
#random forest
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=10,criterion="entropy")
y_pred=rfc.fit(X_train,y_train.ravel()).predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)


[[16  0  0]
 [ 0 18  1]
 [ 0  1 14]]
