In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
veriler=pd.read_csv("odev_tenis.csv")

In [135]:
len(veriler)

14

In [151]:
#encoder : kategorik--> numeric
from sklearn import preprocessing
labelEnc = preprocessing.LabelEncoder()
oneHotEnc = preprocessing.OneHotEncoder()


outlook=veriler.iloc[:,0]
outlook=labelEnc.fit_transform(outlook)
outlook=oneHotEnc.fit_transform(outlook.reshape(-1,1)).toarray()
outlook=pd.DataFrame(data=outlook,columns=["overcast","rainy","sunny"])

windy=veriler.iloc[:,3]
windy=labelEnc.fit_transform(windy)
windy=pd.DataFrame(data=windy,columns=["windy"])

play=veriler.iloc[:,-1:].values
play=labelEnc.fit_transform(play)
play=pd.DataFrame(data=play,columns=["play"])

'''
#tüm değerleri tek seferde encode edebiliriz
veriler2=veriler.apply(labelEnc.fit_transform)
'''

x_veri =pd.concat([windy,play,outlook,veriler.iloc[:,1]],axis=1)
y_veri=veriler.iloc[:,2]


c:\Users\hasan\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [165]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x_veri,y_veri,test_size=0.33,random_state=0)

In [166]:
from sklearn.linear_model import LinearRegression
regressor =LinearRegression()

regressor.fit(x_train,y_train)

tahmin=regressor.predict(x_test)

In [ ]:
tahmin

array([84.45365573, 63.93839954, 85.76050662, 64.21013241, 75.06793322])

In [155]:
y_test

8     70
6     65
4     80
11    90
2     86
Name: humidity, dtype: int64

In [160]:
#backward elimination

import statsmodels.api as sm
X=np.append(arr=np.ones((len(veriler),1)).astype(int),values=x_veri,axis=1)
X_liste=x_veri.iloc[:,[0,1,2,3,4,5]].values
X_liste=np.array(X_liste,dtype=float)
model = sm.OLS(y_veri,X_liste).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Tue, 26 Aug 2025   Prob (F-statistic):              0.661
Time:                        00:37:01   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.593     -20.698      12.641
x2            -8.2778      8.029     -1.031      0.333     -26.793      10.237
x3            52.3891     50.214      1.043      0.327     -63.404     168.183
x4            55.6337     45.233      1.230      0.254     -48.673     159.940
x5            49.4291     48.337      1.023      0.336     -62.035     160.893
x6             0.4920      0.597      0.825      0.433      -0.884       1.868
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   2.416
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.823
Skew:                           0.389   Prob(JB):                        0.663
Kurtosis:                       2.103   Cond. No.                     2.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [161]:
#x1 elimine ediliyor
import statsmodels.api as sm
X=np.append(arr=np.ones((len(veriler),1)).astype(int),values=x_veri,axis=1)
X_liste=x_veri.iloc[:,[1,2,3,4,5]].values
X_liste=np.array(X_liste,dtype=float)
model = sm.OLS(y_veri,X_liste).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Tue, 26 Aug 2025   Prob (F-statistic):              0.546
Time:                        00:37:19   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.2865      6.909     -0.910      0.387     -21.916       9.343
x2            36.6564     39.905      0.919      0.382     -53.615     126.927
x3            41.9135     36.464      1.149      0.280     -40.573     124.400
x4            35.1064     39.339      0.892      0.395     -53.884     124.097
x5             0.6484      0.506      1.282      0.232      -0.496       1.793
==============================================================================
Omnibus:                        0.887   Durbin-Watson:                   2.360
Prob(Omnibus):                  0.642   Jarque-Bera (JB):                0.810
Skew:                           0.424   Prob(JB):                        0.667
Kurtosis:                       2.181   Cond. No.                     1.73e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [178]:
x_train,x_test,y_train,y_test=train_test_split(x_veri,y_veri,test_size=0.33,random_state=0)
x_train=x_train.iloc[:,1:]
x_test=x_test.iloc[:,1:]


regressor.fit(x_train,y_train)
tahmin2=regressor.predict(x_test)

In [179]:
tahmin2

array([77.98135142, 68.29304916, 81.05037539, 71.44926132, 75.78905304])

In [180]:
tahmin

array([84.45365573, 63.93839954, 85.76050662, 64.21013241, 75.06793322])

In [181]:
y_test

8     70
6     65
4     80
11    90
2     86
Name: humidity, dtype: int64